In [26]:
##### WEEK 3 -  pYtorch Introduction

# Roadmap:

# Week 3 Goal:
# Understand how Neural Networks work and train a simple model

# Topics:

# PyTorch basics
# What is PyTorch
# Tensors
# Tensor operations
# Neural Network basics
# Layers
# Activation functions
# Forward pass
# Build first Neural Network
# Training loop
# Loss function
# Optimizer
# Backpropagation
# Save and load model


#### Day 1 — PyTorch Basics

# First understand:

# What is PyTorch?

# PyTorch is a deep learning framework.

# Similar to:

# Pandas → Data handling

# Scikit-learn → Traditional ML

# PyTorch → Neural Networks / Deep Learning

# In MLOps later:

# PyTorch Model
#       |
#       ↓
# Save model
#       |
#       ↓
# MLflow tracking
#       |
#       ↓
# Docker API
#       |
#       ↓
# Kubernetes deployment

# 1 install check

import torch

print(torch.__version__)

# 2 create tensor

# Tensor is PyTorch's main data structure.

# Think:

# NumPy array = ndarray

# PyTorch = Tensor

# Example:

x = torch.tensor([1,2,3,4])

x

# 3 Tensor type

x.dtype


# 4 Tensor shape

x.shape

# 5 create matrix tensor

matrix = torch.tensor([
    [1,2],
    [3,4]
])

matrix

matrix.shape

# 6 Tensor operations

a = torch.tensor([1,2,3])

b = torch.tensor([4,5,6])

a+b #addition

a*b #multiplication

# 7 Random Tensor

random_tensor = torch.rand(3,3)

random_tensor


##### Week 3 Day 2 — Neural Network Basics #####

# 1 Import PyTorch
import torch

from torch import nn #nn means neural network module which provides layers, loss functions, models

# 2 Create simple Data

x = torch.tensor([
    [1],
    [2],
    [3],
    [4],
], dtype=torch.float32)

y = torch.tensor([
    [2],
    [4],
    [6],
    [8]
], dtype=torch.float32)

x

y

# 3 Understand Neural Network Layer

# A simple neural network:

# Input

#   |
#   |
# Linear Layer

#   |
#   |
# Output

# Linear layer:

# nn.Linear()

# means:

# It learns:

# weight
# +
# bias

# 4 Create first neural network

class SimpleModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(
            1,
            1
        )


    def forward(self, x):

        return self.linear(x)

# 5 Create model

model = SimpleModel()

model

# 6 Make Prediction

prediction = model(x)

prediction

# 7 Check model parameters 

for param in model.parameters():
    print(param)



##### Week 3 Day 3 — Training Loop #####

# 1 import 

import torch
from torch import nn

# 2 Create Data

x = torch.tensor([
    [1],
    [2],
    [3],
    [4]
], dtype=torch.float32)


y = torch.tensor([
    [2],
    [4],
    [6],
    [8]
], dtype=torch.float32)

# 3 Create Model

class SimpleModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.linear = nn.Linear(
            1,
            1
        )


    def forward(self,x):

        return self.linear(x)

model = SimpleModel()

# 4 Loss Function

loss_fn = nn.MSELoss() # for regression

# 5 Optimizer

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)


# 6 Training Loop

epochs = 100

for epoch in range(epochs):
    #forward pass
    prediction = model(x)

    #calculate loss

    loss = loss_fn(
        prediction,
        y
    )

    # Reset gradients

    optimizer.zero_grad()

    # Backpropagation

    loss.backward()

    # Update weights

    optimizer.step()

    if epoch % 10 == 0:
        print(
            epoch,
            loss.item()
        )

# 7 Test Model

model(x)


##### Week 3 Day 4 — Save and Load PyTorch Models #####

# 1 Create and Train Model Again

import torch
from torch import nn

x = torch.tensor([
    [1],
    [2],
    [3],
    [4]
], dtype=torch.float32)


y = torch.tensor([
    [2],
    [4],
    [6],
    [8]
], dtype=torch.float32)


class SimpleModel(nn.Module):

    def __init__(self):

        super().__init__()

        self.linear = nn.Linear(
            1,
            1
        )


    def forward(self,x):

        return self.linear(x)

model = SimpleModel()

# 2 Train Quickly

loss_fn = nn.MSELoss() #loss

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
) #optimizer 

for epoch in range(100): #train

    prediction = model(x)

    loss = loss_fn(
        prediction,
        y
    )

    optimizer.zero_grad()

    loss.backward()

    optimizer.step() 


# 3 Save Model

torch.save(
    model.state_dict(),
    "/home/malik/mlops-practice/models/simple_model.pth"
)

import os #verify model saved

os.listdir("/home/malik/mlops-practice/models")

new_model = SimpleModel() # load the model

new_model.load_state_dict(
    torch.load(
        "/home/malik/mlops-practice/models/simple_model.pth"
    )
)

new_model.eval() #set inference mode

new_model(x)



##### Week 3 Day 5 — Model Inference Practice #####

# 1 import 
import torch
from torch import nn

# 2 Create Same Model Architecture

class SimpleModel(nn.Module):
    def __init__(self):

        super().__init__()

        self.linear = nn.Linear(
            1,
            1
        )


    def forward(self,x):

        return self.linear(x)

# 3 Create empty model

model = SimpleModel()

model

# 4 Load Trained Model

model.load_state_dict(
    torch.load(
        "/home/malik/mlops-practice/models/simple_model.pth"
    )
)

# 5 Put Model in Evaluation Mode

model.eval()

# 6 Create New Data

new_data = torch.tensor(
    [
        [5],
        [10],
        [20]
    ],
    dtype=torch.float32
)

# 7 Prediction

with torch.no_grad():
    prediction = model(new_data)
prediction

# 8 Convert Tensor Output

prediction.numpy()

# or

prediction.tolist()


2.12.1+cu130
Parameter containing:
tensor([[0.6703]], requires_grad=True)
Parameter containing:
tensor([-0.9798], requires_grad=True)
0 33.22901153564453
10 1.2511565685272217
20 0.40102943778038025
30 0.3575769364833832
40 0.3362436294555664
50 0.3166591227054596
60 0.2982275187969208
70 0.2808690667152405
80 0.2645210921764374
90 0.24912454187870026


tensor([[ 9.3734],
        [17.8523],
        [34.8103]])